library(data.table)
library(rtracklayer)
library(GenomicRanges)
library(ggpubr)

theme_set(theme_bw() + 
    theme(axis.text=element_text(size=14),
          axis.title=element_text(size=16,face="bold")))


#### First clock: Using age-correlated sites from DSS

# Import methylation data and manually build annotation data

meth_file <- as.data.frame(fread(file = "E:/anole/CpG/processed/labeled_allSites_stranded.tab", header = TRUE, sep = "\t"))

annotations <- data.frame("ID" = c("S10","S15","S19","S23","S28","S33","S41","S46","S49","S51","S53","S61","S62","S64","S66","S67",
                                   "S70","S76","S84","S85","S95","S96", "S107","S110","S111","S116","S117","S120","S122","S125","S126",
                                   "S127","S128","S129","S131","S132","S133"),
                          "ages" = c(36,36,36,36,36,36,48,48,48,48,48,48,18,18,18,18,18,18,1,1,1,1,7,7,7,7,7,7,7,7,7,60,60,60,60,60,60),
                          "sex" = as.factor(c("F","F","F","M","M","F","M","F","M","F","M","F","M","F","F","F","M","M","F","M","F","M","M","F","F","F","F","M","M","M","M","M","M","F","M","F","F")))

# Create genomicranges for methylation matrix

meth.gr <- GRanges(seqnames = meth_file$chr, 
                   ranges = IRanges(start = meth_file$start, end = meth_file$end),
                   strand = "*", mcols = meth_file[,c(4:41)] )
rm(meth_file)
gc()

# Read in age DMCs generated by DSS

logSites <- import.bed("~/Parrott_Lab/AnoleAge/Fig1.1-DSSLogAge/data/LogAgeSites_smoothed200.bed")

# Overlap aDMCs with methylation matrix to get beta values 

logSites.meth <- subsetByOverlaps(meth.gr, logSites, type = "end", maxgap = -1L)

# format aDMC methylation matrix and impute using K-nearest neighbors (k=6 due to lower "treatment" group size)

logSites.df <- as.data.frame(logSites.meth)[,-c(1,2,3,4,5,6)]
rownames(logSites.df) <- paste0(seqnames(logSites.meth), ".", logSites.meth@ranges@start)
imputed <- impute::impute.knn(as.matrix(logSites.df)[,-c(4,37)], k = 6, rowmax = 0.75)

t.logSites <- as.data.frame(t(imputed$data))

## Load glmnet and create index vector specifying which samples are held out for use in the test set

library(glmnet)

index <- c(1,7,10,13,16,19,20,24,29,32,35)

# Remove low-coverage (non-imputable) samples from annotation file

annotations.clean <- annotations[-c(4,37),]
annotations.clean[index,]

#dividing into training and test sets
test.CpG <- as.matrix(t.logSites)[index,] ##choose >= one individual from each age/sex group
test.age <- annotations.clean$ages[index]

train.CpG <- as.matrix(t.logSites)[-index,] ## take all that are not in the test set
train.age <- annotations.clean$ages[-index]


set.seed(1998) #setting seed

#using 6 fold cross validation to estimate the lambda parameter 
age.cv <- cv.glmnet(train.CpG, 
                    as.matrix(log(train.age)),
                    alpha=0, nfolds=6, family="gaussian")

plot(age.cv)

#define the lambda parameter
best_lambda <- age.cv$lambda.min

##run elastic net
CpG.model <- glmnet(train.CpG, 
                    as.matrix(log(train.age)),
                    alpha=0, family="gaussian", nlambda=100)

#coefficients for fitted model
age_coeff <- coef(CpG.model, s=best_lambda)

# intercept and effect sizes

age_coeff[1]

effectSizes <- data.frame("Num" = c(1:length(rownames(logSites.df))), "site" = rownames(logSites.df), "beta" = age_coeff@x[-1])

write.csv(effectSizes, "~/Parrott_Lab/AnoleAge/Supp/dmcClock.csv")

#fitted values
fitted <- predict(CpG.model, as.matrix(train.CpG), s=best_lambda)
actual.fitted <- data.frame(exp(fitted), train.age)

#calculate R2 for fitted data
R2.train <- cor(fitted, train.age)^2

##get the error associated with each predicted ages
actual.fitted$trainerrors <- (actual.fitted$s1 - actual.fitted$train.age)
actual.fitted$abserror <- abs(actual.fitted$trainerrors)
CpG.train_error <- mean(actual.fitted$abserror)

#predicted values for test set
predicted <- predict(CpG.model, test.CpG, s=best_lambda)

#actual by predicted values for training data
actual.dmc.predicted <- data.frame(annotations.clean[index,], exp(predicted), test.age)

##get the error associated with each predicted ages
CpG.predicted_age <- actual.dmc.predicted$s1
CpG.testerror <- (actual.dmc.predicted$s1 - actual.dmc.predicted$test.age)
CpG.abs_error <- abs(CpG.testerror)
CpG.MAE <- median(CpG.abs_error)
CpG.MAE ## 3.94

##CpG Training
plot.CpG.train <- ggplot(data=actual.fitted,aes(x=train.age, y=s1)) +
    geom_point(size = 4, alpha = 0.8) +
    ## use aes(group=1) for single regression line across groups;
    geom_smooth(method=lm, na.rm = TRUE, fullrange= TRUE,
                aes(group=1),colour="black") + theme_bw() + 
    theme(panel.border = element_blank(), panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
    labs(x = "Chronological age (months)", y = "CpG Epigenetic Age (months)", title = "Train Set Predictions") +
    font("xlab", size = 16, color = "black")+
    font("ylab", size = 16, color = "black")+
    font("xy.text", size = 12, color = "black") + xlim(0,75) + ylim(0,75)

plot.CpG.train

##linear model for R2 and pvalue

trainlm <- lm(actual.fitted$s1 ~ actual.fitted$train.age, data = actual.fitted)
summary(trainlm)

##CpG Test

a <- ggplot(data=actual.dmc.predicted,aes(x=test.age, y=s1, color = sex)) +
    geom_point(size = 4, alpha = 0.8) +
    ## use aes(group=1) for single regression line across groups;
    geom_smooth(method= "lm", aes(group=1),colour="black") + 
    labs(x = "Chronological age (months)", y = "Epigenetic Age (months)", color = "Sex") +
    theme(legend.title = element_text(size = 14, face = "bold"),
          legend.text = element_text(size = 12)) +
    xlim(0,62) + ylim(0,62)

a

ggsave(a, filename = "~/Parrott_Lab/AnoleAge/Fig4-Clocks/images/LogAgeSites_RidgeRegression_Test.svg", device = "svg",
       width = 5, height = 4)

##linear model for R2 and pvalue
testlm <- lm(actual.dmc.predicted$s1 ~ actual.dmc.predicted$test.age, data = actual.dmc.predicted)
summary(testlm) ## R2 = 0.874, P = 8.31e-06

median(abs(actual.dmc.predicted$test.age - actual.dmc.predicted$s1)) ## MAE: 3.94
median(abs(actual.dmc.predicted$test.age - actual.dmc.predicted$s1)[which(test.age < 48)]) ## avg error at < 48mo = 1.63 mo (5% of lifespan)





#### Hub-Region clock

## Specify our region of interest (roi) as identified by previous DMR analysis and WGCNA connectivity values

roi <- GRanges("scaffold_5", IRanges(42118000, 42125000))

# Subset meth matrix by those sites inside roi

meth.roi <- subsetByOverlaps(meth.gr, roi, type = "within")

roi.mat <- as.data.frame(t(as.data.frame(meth.roi)[,-c(1,3,4,5)]))
colnames(roi.mat) <- as.character(roi.mat[1,])

# combine with annotations

roi.df.clean <- data.frame(annotations, roi.mat[c(-1,-2),])
roi.df.clean[,c(-1,-2,-3)] <- apply(roi.df.clean[,c(-1,-2,-3)], 2, as.numeric)

# get correlation coefficients from all sites within region and test significance

cortest <- psych::corr.test(roi.df.clean[,c(-1,-2,-3)], roi.df.clean$ages, method = "pearson", ci = FALSE)
cor.df <- data.frame("site" = colnames(roi.df.clean)[c(-1,-2,-3)], "r" = cortest$r, "p" = cortest$p.adj)

cor.df$site <- as.numeric(stringr::str_remove_all(cor.df$site, "X"))
cor.df$sig <- ifelse(cor.df$p < 0.05, "*", "")

sig <- which(cor.df$p < 0.05)

cor.df$missing <- colSums(is.na(roi.df.clean[,-c(1,2,3)]))

cor.df.clean <- cor.df[-which(cor.df$missing > 20),] # remove sites with high missingness in this region

# plot visualization of subregion containing most informative clocksites

roiCorPlot <- ggplot(cor.df.clean, aes(x = site, y = r, color = r, label = sig)) + 
    geom_point() + geom_line() + 
    geom_vline(xintercept = 42122400, color = "magenta", linetype = "dashed") + 
    geom_vline(xintercept = 42123100, color = "magenta", linetype = "dashed") +
    xlab("Base Coordinates on Chr5") + ylab("Pearson's r") +
    scale_color_gradient2(low = "blue", mid = "white", high = "red") + ylim(-1,1) +
    geom_text(aes(x = site, y = -1), color = "black", size = 8) + 
    geom_hline(yintercept = 0, size = 1.5, linetype = "dashed") +
    theme(panel.grid.major = element_blank(), legend.position = "none") + 
    labs(color = "Cor")
roiCorPlot

ggsave(roiCorPlot, filename = "~/Parrott_Lab/AnoleAge/Fig4-Clocks/images/HubRegion_corPlot.svg", device = "svg",
       width = 7, height = 4)

sig.roi <- data.frame(roi.df.clean[-c(4,37),c(2,3)], roi.df.clean[-c(4,37),sig+3])

## Now generate regular linear model with just average methylation across all sites within the identified bounds

index <- c(1,7,10,13,16,19,20,24,29,32,35) # same index as first clock

avgs.all <- data.frame(annotations.clean, 
                       "roi.avgs" = rowMeans(sig.roi[,-c(1,2)], na.rm = TRUE))

## Look at trend in methylation values

avgs.roi.trend <- ggplot(avgs.all, aes(x = ages, y = roi.avgs, color = sex)) + geom_point(size = 4) +
    geom_smooth(method = "lm", formula = y ~ log(x), aes(group = 1), color = "black") +
    labs(x = "Chronological Age (months)", y = "Avg. Methylation in Region", color = "Sex") +
    theme(legend.text=element_text(size=12),
          legend.title=element_text(size=14,face="bold")) + ylim(0,100)

avgs.roi.trend

ggsave(avgs.roi.trend, filename = "~/Parrott_Lab/AnoleAge/Fig4-Clocks/images/HubRegion_avgPlot.svg", device = "svg",
       width = 5, height = 4)

## calculate region-wide average of sites in each sample

avgs.train <- rowMeans(sig.roi[-index,-c(1,2)], na.rm = TRUE)
avgs.test <- rowMeans(sig.roi[index,-c(1,2)], na.rm = TRUE)

avg.lm.train <- lm(log(annotations.clean$ages[-index]) ~ avgs.train)
summary(avg.lm.train) ## R2 = 0.85, p = 1.35e-08

write.csv(as.data.frame(coefficients(avg.lm.train)), "~/Parrott_Lab/AnoleAge/Supp/roiClock.csv")

avg.lm.test <- lm(log(annotations.clean$ages[index]) ~ avgs.test)
summary(avg.lm.test) ## R2 = 0.85, p = 1.35e-08

avg.train.df <- data.frame(annotations.clean[-index,], "predicted" = exp(predict(avg.lm.train)))

ggplot(avg.train.df, aes(x = ages, y = predicted, color = sex)) + geom_smooth(method = "lm", aes(group = 1), color = "black", alpha = 0.15) + geom_point() +
                      ylab("Predicted Age") + xlab("Actual Age") + labs(title = "Hub Region - Training set")

avg.test.df <- data.frame(annotations.clean[index,], 
                           "predicted" = exp(predict(avg.lm.test, newdata = data.frame("means" = rowMeans(sig.roi[index,-c(1,2)], na.rm = TRUE)))))


resids <- avg.test.df$ages - avg.test.df$predicted
MAE <- median(abs(resids))
MAE ## MAE: 3.59

roi.clock <- ggplot(avg.test.df, aes(x = ages, y = predicted, color = sex)) + 
    geom_point(size = 4, alpha = 0.8) + ylim(0,60) +
    geom_smooth(method = "lm", aes(group = 1), color = "black", alpha = 0.3) + 
    theme(legend.text=element_text(size=12),
                        legend.title=element_text(size=14,face="bold")) +
    labs(x = "Chronological Age (months)", y = "Epigenetic Age (months)", color = "Sex")

roi.clock

ggsave(roi.clock, filename = "~/Parrott_Lab/AnoleAge/Fig4-Clocks/images/hubRegion_AVGclock.svg", device = "svg",
       width = 5, height = 4)













#### Second clock: Using blue module Eigenvalue
library(ggfortify)

annotations <- data.frame("ID" = c("S10","S15","S19","S23","S28","S33","S41","S46","S49","S51","S53","S61","S62","S64","S66","S67",
                                   "S70","S76","S84","S85","S95","S96", "S107","S110","S111","S116","S117","S120","S122","S125","S126",
                                   "S127","S128","S129","S131","S132","S133"),
                          "ages" = c(36,36,36,36,36,36,48,48,48,48,48,48,18,18,18,18,18,18,1,1,1,1,7,7,7,7,7,7,7,7,7,60,60,60,60,60,60),
                          "sex" = as.factor(c("F","F","F","M","M","F","M","F","M","F","M","F","M","F","F","F","M","M","F","M","F","M","M","F","F","F","F","M","M","M","M","M","M","F","M","F","F")))

rownames(annotations) <- annotations$ID

## Import data frame containing methylation values at the identified blue module

blueMod <- read.table("~/Parrott_Lab/AnoleAge/WGCNA/data/blue.mat", sep = "\t")

# Calculate eigenvalue and look at trend with age

bluePC <- prcomp(as.matrix(blueMod), center = TRUE, scale. = TRUE)

bluePC.df <- merge(annotations, bluePC$x[,c(1,2,3)], by = 0, sort = FALSE)

ggplot(bluePC.df, aes(x = ages, y = PC1, fill = ages, shape = sex)) + geom_point(pch = 21, color = "black", size = 3) + 
    scale_fill_gradient(low = "grey80", high = "blue4")

ggplot(bluePC.df, aes(x = ages, y = PC1, color = sex)) + xlab("Age") + ylab("Blue Module Eigenvalue") + 
    geom_point()# + geom_smooth(method = "lm", formula = y ~ log(x), se = FALSE)

## Train model on eigenvalues
lm.PC <- lm(data = bluePC.df[-index,], formula = log(ages) ~ PC1)
summary(lm.PC) ## R2 = 0.76, p = 1.81e-08

write.csv(as.data.frame(coefficients(lm.PC)), "~/Parrott_Lab/AnoleAge/Supp/wgcnaClock.csv")

bluePC.predicted <- data.frame(bluePC.df[index,], "est" = predict(lm.PC, newdata = bluePC.df[index,]))

# Plot actual vs predicted ages

blue.clock <- ggplot(bluePC.predicted, aes(x = ages, y = exp(est), color = sex)) + ylim(0,60) +
                  geom_smooth(method = "lm", aes(group = 1), color = "black", alpha = 0.3) + 
                  geom_point(size = 4, alpha = 0.8) +
                  theme(legend.text=element_text(size=12),
                        legend.title=element_text(size=14,face="bold")) +
                  labs(color = "Sex", x = "Chronological Age (months)", y = "Epigenetic Age (months)")
blue.clock

lm.PC.test <- lm(data = bluePC.df[index,], formula = log(ages) ~ PC1)
summary(lm.PC.test) ## R2 = 0.91, p = 1.81e-08


ggsave(blue.clock, filename = "~/Parrott_Lab/AnoleAge/Fig4-Clocks/images/BlueMod_PCclock_PredictVsActual.svg", device = "svg",
       width = 5, height = 4)
















#### Third clock: Using Elastic Net
library(glmnet)
library(data.table)

annotations <- data.frame("ID" = c("S10","S15","S19","S23","S28","S33","S41","S46","S49","S51","S53","S61","S62","S64","S66","S67",
                                   "S70","S76","S84","S85","S95","S96", "S107","S110","S111","S116","S117","S120","S122","S125","S126",
                                   "S127","S128","S129","S131","S132","S133"),
                          "ages" = c(36,36,36,36,36,36,48,48,48,48,48,48,18,18,18,18,18,18,1,1,1,1,7,7,7,7,7,7,7,7,7,60,60,60,60,60,60),
                          "sex" = as.factor(c("F","F","F","M","M","F","M","F","M","F","M","F","M","F","F","F","M","M","F","M","F","M","M","F","F","F","F","M","M","M","M","M","M","F","M","F","F")))

rownames(annotations) <- annotations$ID

# Read in data and impute

#CpG <- as.data.frame(fread("E:/anole/CpG/total_mat_30L.data", header= TRUE, sep = "\t"))
#CpGsites <- as.data.frame(fread("E:/anole/CpG/total_meth_30L.data", header= TRUE, sep = "\t"))[,c(1,2,3)]
#
#CpG <- data.frame(CpGsites, CpG)
#colnames(CpG)[c(4:40)] <- stringr::str_replace_all(colnames(CpG)[c(4:40)], "X", "S")
#
#CpGnames <- paste0(CpG$chr, ".", CpG$start)
#row.names(CpG) <- CpGnames
#CpG <- CpG[,-c(1,2,3)] ##select everything except for the first four columns (which is the CpGnames)

## Insert sample annotations - sex transformed to numeric to avoid overhead associated with character rbind... 0=F,1=M
#head(CpG)
#
### Check % of missing sites in each sample
#
#for (i in 1:length(CpG[1,])){
#    print(colnames(CpG)[i])
#    print(sum(is.na(CpG[,i])) / length(CpG[,i]))
#}

### Now impute values using the mean from all samples
#
#k <- which(is.na(CpG), arr.ind=TRUE)
#CpG[k] <- rowMeans(CpG, na.rm=TRUE)[k[,1]]
#head(CpG)
#anole_CpG <- as.data.frame(t(CpG))
#rm(CpG, CpGsites)

## KNN imputation - pre-performed

#knn <- impute::impute.knn(as.matrix(CpG[,-c(4,37)]), maxp = 25000)
#CpG.imputed <- data.frame(knn$data)
#fwrite(CpG.imputed, file = "E:/anole/CpG/processed/80PercMissing_imputed.data",
#       row.names = TRUE, col.names = TRUE, sep = "\t")



CpG.imputed <- as.data.frame(fread("E:/anole/CpG/processed/80PercMissing_imputed.data", header = TRUE)) # data pre-imputed in above commented code block
rownames(CpG.imputed) <- CpG.imputed$V1
CpG.imputed <- CpG.imputed[,-1]
sample_names <- colnames(CpG.imputed)

anole_CpG <- as.data.frame(t(CpG.imputed))

##break into ages and methylation values
anole_ages <- annotations.clean$ages

### Hand-pick test set
index <- c(1,7,10,13,16,19,20,24,29,32,35)
annotations.clean[index,]

#dividing into training and test sets
test.CpG <- as.matrix(anole_CpG)[index,] ##choose one individual from each age/sex group
test.age <- anole_ages[index]

train.CpG <- as.matrix(anole_CpG)[-index,] ## take all that are not in the test set
train.age <- anole_ages[-index]


set.seed(1998) #setting seed
#using 6 fold cross validation to estimate the lambda parameter 
age.cv <- cv.glmnet(train.CpG, 
                    as.matrix(log(train.age)),
                    alpha=0.5, nfolds=6, family="gaussian")

#define the lambda parameter
best_lambda <- age.cv$lambda.min

##run elastic net
CpG.model <- glmnet(train.CpG, 
                    as.matrix(log(train.age)),
                    alpha=0.5, family="gaussian", nlambda=100)

#coefficients for fitted model
age_coeff <- coef(CpG.model, s=best_lambda)

#fitted values
fitted <- predict(CpG.model, as.matrix(train.CpG), s=best_lambda)
actual.fitted <- data.frame(exp(fitted), train.age)

#calculate R2 for fitted data
R2.train <- cor(fitted, train.age)^2

##get the error associated with each predicted ages
actual.fitted$trainerrors <- (actual.fitted$s1 - actual.fitted$train.age)
actual.fitted$abserror <- abs(actual.fitted$trainerrors)
CpG.train_error <- mean(actual.fitted$abserror)

#predicted values for test set
predicted <- predict(CpG.model, test.CpG, s=best_lambda)

#actual by predicted values for training data
actual.predicted <- data.frame(annotations.clean[index,], exp(predicted), test.age)

##get the error associated with each predicted ages
CpG.predicted_age <- actual.predicted$s1
CpG.testerror <- (actual.predicted$s1 - actual.predicted$test.age)
CpG.abs_error <- abs(CpG.testerror)
CpG.MAE <- median(CpG.abs_error)
CpG.MAE ## MAE: 3.61

CpG.MAE.wild <- median(CpG.abs_error[which(anole_ages[index] < 40)])
CpG.MAE.wild ## 2.22

##PULLING OUT CLOCK SITES
age.coeffs <- coef(CpG.model, s = best_lambda)
age.coeffs.df <- data.frame(name = age.coeffs@Dimnames[[1]][age.coeffs@i + 1], coefficient = age.coeffs@x)

write.csv(age.coeffs.df, file = "~/Parrott_Lab/AnoleAge/Supp/elnetClock.csv")

#### PLOT CLOCKs
library(ggpubr)

##CpG Training
plot.CpG.train <- ggplot(data=actual.fitted,aes(x=train.age, y=s1)) +
    geom_point(size = 4, alpha = 0.8) +
    ## use aes(group=1) for single regression line across groups;
    geom_smooth(method=lm, na.rm = TRUE, fullrange= TRUE,
                aes(group=1),colour="black") + theme_bw() + 
    theme(panel.border = element_blank(), panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
    labs(x = "Chronological age (months)", y = "CpG Epigenetic Age (months)", title = "Train Set Predictions") +
    font("xlab", size = 16, color = "black")+
    font("ylab", size = 16, color = "black")+
    font("xy.text", size = 12, color = "black") + xlim(0,75) + ylim(0,75)

plot.CpG.train

##linear model for R2 and pvalue

trainlm <- lm(actual.fitted$s1 ~ actual.fitted$train.age, data = actual.fitted)
summary(trainlm)

## Plot CpG Test

plot.CpG.test <- ggplot(data=actual.predicted,aes(x=test.age, y=s1, color = sex)) +
    geom_point(size = 4, alpha = 0.8) +
    geom_smooth(method=lm, na.rm = TRUE, fullrange= TRUE, aes(group=1),colour="black", alpha = 0.3) + 
    labs(x = "Chronological age (months)", 
         y = "Epigenetic Age (months)", 
         color = "Sex") +
    theme(legend.text = element_text(size = 12),
          legend.title = element_text(size = 14, face = "bold")) +
     xlim(0,60) + ylim(0,60)

plot.CpG.test

ggsave(plot.CpG.test, filename = "~/Parrott_Lab/AnoleAge/Fig4-Clocks/images/ElasticNet_Test.svg", device = "svg",
       width = 5, height = 4)


##linear model for R2 and pvalue
testlm <- lm(actual.predicted$s1 ~ actual.predicted$test.age, data = actual.predicted)
summary(testlm) ## R2 = 0.86, P = 0.0003

testlm <- lm(actual.predicted$s1[which(annotations$ages[index] < 40)] ~ actual.predicted$test.age[which(annotations$ages[index] < 40)], data = actual.predicted)
summary(testlm) ## R2 = 0.98, P = 0.0003

sexlm <- lm(data = actual.predicted[which(anole_ages[index] < 40),],  
                formula = s1 ~ ages*sex)
summary(sexlm)

median(abs(actual.predicted$test.age - actual.predicted$s1)) ## MAE: 3.61
median(abs(actual.predicted$test.age - actual.predicted$s1)[which(test.age < 48)]) ## avg error at < 48mo = 3.5 mo (5% of lifespan)

#write.csv(actual.predicted, 
 #         file = "~/Parrott_Lab/AnoleAge/Fig4-Clocks/data/ElasticNet_TestSet_Predictions.csv",
 #         row.names = FALSE)


##### Look at error across all clocks with respect to age and sex (Supplementary Mat.)

# Get errors from each clock and combine

elnet_error <- actual.predicted$s1 - actual.predicted$ages
bluemod_error <- exp(bluePC.predicted$est) - bluePC.predicted$ages
hubregion_error <- avg.test.df$predicted - avg.test.df$ages
dmc_error <- actual.dmc.predicted$s1 - actual.dmc.predicted$ages

allErrors <- data.frame(annotations.clean[index,], 
                        "elasticNet" = elnet_error,
                        "aDMCs" = dmc_error,
                        "blueModule" = bluemod_error,
                        "hubRegion" = hubregion_error)

# Format to plot

allErrors$bins <- ifelse(allErrors$ages < 48, "1-36 Mnth", "48-60 Mnth")

allErrors.long <- tidyr::pivot_longer(allErrors, cols = c(4:7), names_to = "Clock", values_to = "Errors")

allErrors.long$Clock <- factor(allErrors.long$Clock, levels = c("elasticNet", "aDMCs", "blueModule", "hubRegion"))

s <- ggplot(allErrors.long, aes(x = bins, y = Errors)) + geom_boxplot(outlier.alpha = 0, aes(color = Clock)) + 
        geom_jitter(color = "black", width = 0.2, height = 0) + facet_wrap(~Clock) + 
        theme(legend.position = "none") + labs(x = "") + scale_color_manual(values = c("red", "blue", "forestgreen", "purple")) + 
    stat_compare_means(label.x = 0.7, label.y = 15) + ylim(-35, 18)
s
    
ggsave(s, filename = "~/Parrott_Lab/AnoleAge/Fig4-Clocks/images/Errors_by_ageClass.svg", device = "svg",
       width = 6, height = 5)

#### Quantify error differences across age via means and t-tests

mean(allErrors.long$Errors[which(allErrors.long$bins == "1-36 Mnth")])
mean(allErrors.long$Errors[which(allErrors.long$bins == "48-60 Mnth")])

t.test(allErrors.long$Errors[which(allErrors.long$bins == "1-36 Mnth")], 
       allErrors.long$Errors[which(allErrors.long$bins == "48-60 Mnth")])

mean(abs(allErrors.long$Errors[which(allErrors.long$bins == "1-36 Mnth")]))
mean(abs(allErrors.long$Errors[which(allErrors.long$bins == "48-60 Mnth")]))

t.test(abs(allErrors.long$Errors[which(allErrors.long$bins == "1-36 Mnth")]), 
       abs(allErrors.long$Errors[which(allErrors.long$bins == "48-60 Mnth")]))


#### Quantify error differences across sex via means and t-tests

mean(allErrors.long$Errors[which(allErrors.long$sex == "F")])
mean(allErrors.long$Errors[which(allErrors.long$sex == "M")])

t.test(allErrors.long$Errors[which(allErrors.long$sex == "F")], 
       allErrors.long$Errors[which(allErrors.long$sex == "M")])

mean(abs(allErrors.long$Errors[which(allErrors.long$sex == "F")]))
mean(abs(allErrors.long$Errors[which(allErrors.long$sex == "M")]))

t.test(abs(allErrors.long$Errors[which(allErrors.long$sex == "F")]), 
       abs(allErrors.long$Errors[which(allErrors.long$sex == "M")]))

s2 <- ggplot(allErrors.long, aes(x = sex, y = Errors)) + geom_boxplot(outlier.alpha = 0, aes(color = Clock)) + 
        geom_jitter(color = "black", width = 0.2, height = 0) + facet_wrap(~Clock) + 
        theme(legend.position = "none") + labs(x = "") + scale_color_manual(values = c("red", "blue", "forestgreen", "purple")) + 
    stat_compare_means(label.x = 0.7, label.y = 15) + ylim(-35, 18)
s2
    
ggsave(s2, filename = "~/Parrott_Lab/AnoleAge/Fig4-Clocks/images/Errors_by_sex.svg", device = "svg",
       width = 6, height = 5)



#### LOOCV

# initialize empty vectors to be populated during loop

dataset<-as.matrix(1:35)
age <- log(anole_ages)
CpG_values <- anole_CpG
##create lists to input data values into
BestLambdas<-c()
R2trains<-c()
Train_MAE<-c()
Test_MAE<-c()
sites <- c()
Predicted_age <- c()
sample_names <- row.names(anole_CpG)
#load library

library(dplyr)
##elastic net for loop -- modified from SG script

for (i in 1:nrow(dataset)){
    print(paste0("Running model ", i, "..."))
    train.CpG <- CpG_values[-i,] ##train is all except the 1 test sample per iteration
    test.CpG <- CpG_values[i,] ##test is left out sample
    test.age <- age[c(i)]
    train.age <- age[c(-i)]
    set.seed(1998) #setting seed
    ##run elastic net
    model <- glmnet(as.matrix(train.CpG), 
                    as.matrix(train.age),
                    alpha=0.5, family="gaussian", nlambda=100)
    #coefficients for fitted model
    age_coeff <- coef(model, s=best_lambda)
    #fitted values
    fitted <- predict(model, as.matrix(train.CpG), s=best_lambda)
    actual.fitted <- data.frame(exp(fitted), train.age)
    #calculate R2 for fitted data
    R2.train <- cor(fitted, train.age)^2
    R2trains <- append(R2trains,R2.train) ##write R2 from each iteration to list
    ##get the error associated with each predicted ages
    actual.fitted$trainerrors <- (actual.fitted$s1 - actual.fitted$train.age)
    actual.fitted$abserror <- abs(actual.fitted$trainerrors)
    train_error <- mean(actual.fitted$abserror)
    Train_MAE <-append(Train_MAE,train_error)
    #predicted values for test set
    predicted <- predict(model, as.matrix(test.CpG), s=best_lambda)
    #actual by predicted values for training data
    actual.predicted <- data.frame(exp(predicted), test.age)
    ##get the error associated with each predicted ages
    predicted_age <- actual.predicted$s1
    Predicted_age <- append(Predicted_age,predicted_age)
    testerror <- (actual.predicted$s1 - actual.predicted$test.age)
    abs_error <- abs(testerror)
    Test_MAE <- append(Test_MAE, abs_error)
    age.coeffs <- coef(model, s =best_lambda)
    sites <- append(sites,(name = age.coeffs@Dimnames[[1]][age.coeffs@i + 1]))
}

##merge output into one dataset
merged_info <- data.frame(sample_names, anole_ages, R2trains, Train_MAE, Predicted_age, Test_MAE)
merged_info$sex <- annotations$sex[-c(4,37)]

#Total_MAE <- merged_info$
merged_info$indError <- merged_info$anole_ages - merged_info$Predicted_age

write.table(merged_info, file = "~/Parrott_Lab/AnoleAge/Fig4-Clocks/data/loocv_results.tsv",
            sep = "\t", quote = FALSE, col.names = TRUE)

merged_info <- read.table("~/Parrott_Lab/AnoleAge/Fig4-Clocks/data/loocv_results.tsv",
            sep = "\t", header = TRUE)

# Calculate median absolute error

Total_MAE <- median(abs(merged_info$indError))
WildAge_MAE <- median(abs(merged_info$indError[which(annotations$ages < 40)]))

##write sites out to data frame 
sites <- as.data.frame(sites)
# Count the number of times each site occurs in a clock, and take those that occur >10(?) times
n_occur <- data.frame(table(sites$sites))
commonSites <- n_occur[which(n_occur$Freq > 30),]
commonSites <- commonSites[c(-1,-2),]
write.table(commonSites,"~/Parrott_Lab/AnoleAge/Fig4-Clocks/data/n_occur30_LOOCVsites.tab", quote = FALSE,
            row.names = FALSE, col.names = TRUE, sep = "\t")

## Plot Test Data
LOOCV.test <- ggplot(data = merged_info, 
                     aes(x = anole_ages, y = Predicted_age, color = sex)) + 
    geom_point(size = 4, alpha = 0.8) + geom_smooth(method = "lm", color = "black", alpha = 0.3) +
    labs(x = "Chronological age (months)", y = "Epigenetic Age (months)", color = "Sex") +
    xlim(0,60) + ylim(0,60) + theme(legend.text = element_text(size = 12),
                                    legend.title = element_text(size = 14, face = "bold"))
LOOCV.test

ggsave(LOOCV.test, filename = "~/Parrott_Lab/AnoleAge/Fig4-Clocks/images/LOOCV_actualVSpred.svg", device = "svg",
       width = 5, height = 4)

## Plot error by age
LOOCV.error <- ggplot(data = merged_info, aes(x = anole_ages, y = abs(indError), group = anole_ages)) + geom_boxplot() + 
    theme_bw() + theme(panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
    labs(x = "Chronological age (months)", y = "LOOCV prediction Error") +
    font("xlab", size = 16, color = "black")+
    font("ylab", size = 16, color = "black")+
    font("xy.text", size = 12, color = "black") + xlim(0,65) + ylim(0,42)
LOOCV.error

## Test for sex differences?

ggplot(merged_info, aes(x = anole_ages, y = indError, color = sex, group = anole_ages)) + geom_boxplot() + facet_wrap("sex")

t.test(merged_info$indError[which(merged_info$sex == "M")])

loocv.lm <- lm(data = merged_info, formula = Predicted_age ~ anole_ages)
summary(loocv.lm) ## R2 = 0.66, p = 9.4e-10

## Error increases with age
loocv.lm2 <- lm(data = merged_info, formula = indError ~ anole_ages)
summary(loocv.lm2)

median(merged_info$indError) ## MAE: 3.17

median(merged_info$indError[which(merged_info$anole_ages < 40)])

## Plot Test Data w/o sex
LOOCV.test <- ggplot(data = merged_info, aes(x = anole_ages, y = Predicted_age)) + geom_point(size = 3) + 
    geom_smooth(method = "lm") + 
    theme_bw() + theme(panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
    labs(x = "Chronological age (months)", y = "CpG Epigenetic Age (months)") +
    font("xlab", size = 16, color = "black")+
    font("ylab", size = 16, color = "black")+
    font("xy.text", size = 12, color = "black") + xlim(0,65) + ylim(0,60)# + guides(colour = "none")
LOOCV.test
